version: '2'

services:

    main:
        image: nginx
        depends_on:
            - fpm
        ports:
            - 80
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=80
        volumes:
            - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
            - front
            - back
            - default

    fpm:
        image: piwik
        depends_on:
            - db
        volumes: 
            - ./conf/ssmtp.conf:/etc/ssmtp/ssmtp.conf
            - ./conf/revaliases:/etc/ssmtp/revaliases
    
    db:
        image: puffinrocks/mariadb
        environment:
            MYSQL_ROOT_PASSWORD: piwik
        volumes: 
            - db_data:/var/lib/mysql

volumes:
    db_data:

networks:
    front:
        external:
            name: "puffin_front"
    back:
        external:
            name: "puffin_back"

