version: '2'

services:

    main:
        image: puffinrocks/piwik:3.0.1
        depends_on:
            - fpm
        ports:
            - 80
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=80
            - LETSENCRYPT_HOST
            - LETSENCRYPT_EMAIL
            - LETSENCRYPT_TEST
        networks:
            - front
            - back
            - default
        volumes_from:
            - fpm
        tmpfs:
            - /run
            - /tmp

    fpm:
        image: piwik:3.0.1
        depends_on:
            - db
        networks:
            - back
            - default
        volumes: 
            - static:/var/www/html
        tmpfs:
            - /run
            - /tmp
    
    db:
        image: puffinrocks/mariadb
        environment:
            MYSQL_ROOT_PASSWORD: piwik
        volumes: 
            - db_data:/var/lib/mysql

volumes:
    db_data:
    static:

networks:
    front:
        external:
            name: "puffin_front"
    back:
        external:
            name: "puffin_back"

