version: '2'

services:

    main:
        image: puffinrocks/piwik
        depends_on:
            - fpm
        ports:
            - 80
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=80
        volumes_from:
            - fpm
        networks:
            - front
            - back
            - default

    fpm:
        image: piwik
        depends_on:
            - db
        volumes: 
            - static:/var/www/html
        networks:
            - back
            - default
    
    db:
        image: puffinrocks/mariadb
        environment:
            MYSQL_ROOT_PASSWORD: piwik
        volumes: 
            - db_data:/var/lib/mysql

volumes:
    db_data:
    static:

networks:
    front:
        external:
            name: "puffin_front"
    back:
        external:
            name: "puffin_back"

